- name: install apache2 and php packages for Ubuntu
  apt: 
   name:
     - apache2
     - libapache2-mod-php 
   state: latest
   update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: install apache and php packages for CentOS
  dnf:
   name:
     - httpd
     - php
   state: latest
   update_cache: yes
  when: ansible_distribution == "CentOS"

- name: start httpd (Centos)
  tags: apache, centos,httpd
  service:
    name: httpd
    state: started
  when: ansible_distribution == "CentOS"
